apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-app
  name: java-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app
    spec:
      containers:
        - image: zhouyeahyuqi/java-app:v2
          name: java-app
          resources: {}
status: {}
